### ISSUE TITLE
TypeError: $.argumentsToArray is not a function error

### ISSUE THREAD

**Issue by keith-kurak** [christianbradley/bump-anything#1]
I created a new version file that looks like
```
{
  "version": "1.0.0"
}
```

and created a simple script to bump the version, like:
```
const bumper = require('bump-anything').configure();

bumper.major('build.json').done();
```

But I get the following error
```
/Users/my-username/Github/my-package-name/node_modules/bump-anything/src/configuration.js:34
			var args = $.argumentsToArray(arguments);
			             ^

TypeError: $.argumentsToArray is not a function
    at Configuration.pipeline (/Users/my-username/Github/my-package-name/node_modules/bump-anything/src/configuration.js:34:17)
    at bump (/Users/my-username/Github/my-package-name/node_modules/bump-anything/src/bump-anything.js:43:13)
    at Object.major (/Users/my-username/Github/my-package-name/node_modules/bump-anything/src/bump-anything.js:53:38)
    at Object.<anonymous> (/Users/my-username/Github/my-package-name/build-utils/increment-js-build.js:20:8)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
```

**Comment by Tuizi** [comment]
Same problem here with:

```
const bumper = require("bump-anything").configure();  
bumper.bump("package.json", "minor");
```


```
var args = $.argumentsToArray(arguments);
             ^
TypeError: $.argumentsToArray is not a function at Configuration.pipeline
```
